hostname: 'worker.example.com'
mailing:
  host: 'smtp.example.com'
  port: '465'
  protocol: 'SSL'
  username: 'spammer@example.com'
  password: 'p4ssw0rd'
logging:
  # send logs to this address
  admins:
    - 'spammer@example.com'
  email: True
  level: 'DEBUG'
redis:
    'mail_queue': 'mailmachine'
    'reconnect': true
