#!/usr/bin/env python
import argparse
import hotqueue
import os
import pprint
from email_message import get_connection
from pygments import highlight
from pygments.formatters import TerminalFormatter
from pygments.lexers import JSONLexer
import simplejson

from mailmachine import enqueue, send
from mailmachine.configuration import load_config


def _print(result, colors):
    json = simplejson.dumps(result, sort_keys=True, indent=4)
    if colors:
        print highlight(json, JSONLexer(), TerminalFormatter())
    else:
        pprint.pprint(json)

def do_enqueue(args, config):
    c = config['redis']
    mail_queue = hotqueue.HotQueue(c['mail_queue'], host=c['host'], port=c['port'],
                                   password=c.get('password'))

    mail = simplejson.loads(args.mail_data)
    enqueue(mail_queue, **mail)

def do_mail(args, config):
    mc = config['mail']
    mail = simplejson.loads(args.mail_data)
    connection = get_connection(mc['host'], mc['port'], username=mc['username'],
                                password=mc['password'], use_tls=mc['use_tls'])
    send(connection, **mail)

def do_list(args, config):
    c = config['redis']
    mail_queue = hotqueue.HotQueue(c['mail_queue'], host=c['host'], port=c['port'],
                                   password=c.get('password'))
    mails = []
    for mail in [mail_queue.serializer.loads(c) for c in mail_queue._HotQueue__redis.lrange(mail_queue.key, 0, len(mail_queue)-1)]:
        mail_queue._HotQueue__redis
        mails.append(mail)
    _print(mails, not args.no_colors)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Put mail to mailing queue')
    default_config = '/etc/mailmachine.yaml'
    parser.add_argument('-c', '--config', help='Specify configuration file',
                        default=default_config if os.path.exists(default_config) else None)
    subparsers = parser.add_subparsers(help='Subcommands help')

    enqueue_parser = subparsers.add_parser('enqueue')
    enqueue_parser.add_argument('mail_data')
    enqueue_parser.set_defaults(func=do_enqueue)

    mail_parser = subparsers.add_parser('mail')
    mail_parser.add_argument('mail_data')
    mail_parser.set_defaults(func=do_enqueue)

    list_parser = subparsers.add_parser('list')
    list_parser.add_argument('--no-colors', help='Print result in colors',
                             default=False, action='store_true')
    list_parser.set_defaults(func=do_list)

    args = parser.parse_args()
    config = load_config(args.config)
    args.func(args, config)
